### ISSUE TITLE
I cant get your cool application to work.

### ISSUE THREAD

**Issue by mikeiem** [JulWas797/MandelScope#1]
I am using Visual Studio 2022 on .NET 8.0. I am getting this about FormMain.resx and FormAbout.resx
Severity	Code	Description	Project	File	Line	Suppression State
Error		Couldn't process file FormMain.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	MandelScope		
Severity	Code	Description	Project	File	Line	Suppression State
Error		Couldn't process file FormAbout.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	MandelScope			

can you help me getting running. If you can. I will send you some $$.
Mike Iem

**Comment by JulWas797** [comment]
Hello,

Sorry for the late response. I wasn't able to access my GitHub account, I just finished 2FA recovery.

I will gladly help you. To fix this issue, you need to open the files in windows explorer, select properties, and choose the unlock option (screenshot in Polish). Soon I will also push the newest app version there, as I implemented generation using SSE2 compiler insitrics.

![image](https://github.com/JulWas797/MandelScope/assets/51297298/bdf32c41-d63f-45b4-8791-5b83a1e2d733)

Also, note that I do it totally for free, but if you wanna support me the donation link is available in the about section.

- Julian

**Comment by mikeiem** [comment]
Julian,
I found some Fractal Programs from Product Managers when we launched .NET. Some smart Microsoft guys wrote this.
What was cool about this was you take your mouse and drag into the fractal just keep going deeper and deeper.
It was written in 2002 so it will take a little work to get it working in .NET 8.0 or .NET Framework 4.8

Hope this helps.
Mike


Michael Iem ***@***.***

**Comment by JulWas797** [comment]
Thanks, I'm gonna check it this evening. Also thanks for the donation!
